### PR TITLE
Added German language file

### PR DESCRIPTION
**Pull request by naxmefy**

### CODE REVIEW

**Comment by IvanRF** [comment]
@naxmefy thanks for sending the translations! 👍 

I check them with Google Translate and found 3 "did you mean", could you check if these have some typos:

`+ShowExtension=Zeige Dateierweiertung`
Zeige Dateierweiterung

`+UpdatingTable=Aktualisiere Tabelle...`
Aktualisierte Tabelle...

`+DevelopedBy=Entwicklet von`
Entwickelt von

**Comment by naxmefy** [comment]
of course

**Comment by naxmefy** [comment]
``` +UpdatingTable=Aktualisiere Tabelle... ```

is correct - coz it means table is currently updating

``` Aktualisierte Tabelle... ``` would mean the table is already updated

**Comment by IvanRF** [comment]
@naxmefy Excellent! Thanks again, as you can see my German is `null` 😄

**Comment by Cappuccino90** [comment]
God damnit. I just translated it in german, too. Discovered this pull request a little too late.

**Comment by IvanRF** [comment]
@Cappuccino90 I just saw your comment on the site and was about to reply. Sorry!

Could you confirm then that this translation is fine?

**Comment by Cappuccino90** [comment]
@IvanRF Yep, I checked every string. The translation is good.

**Pull request merged**
